/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java exporter", 0)}
 * @author AUTOCODE
 * @version $ID: ${pojo.getDeclarationName()} [BASE-LINE] ${date} $
 */
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}