package com.zsq.test.model;
// Generated 2017-1-5 21:41:05 by Hibernate Tools 4.3.5.Final


import java.util.Date;

/**
 * JxNom generated by hbm2java
 */
public class JxNom  implements java.io.Serializable {

 	private String id;
	/**
	 *  * this is doc info
	 */
 	//contract file info.
 	private String htFileId;
 	private String htFileName;
 	private Integer nomStatus;
 	private String orgL1name;
 	private String orgL2name;
 	private String orgName;
 	private Date psDate;
 	private Float q2finalScore;
 	private Float q3finalScore;
 	private Float q4finalScore;
 	private Date submitDate;
 	private Integer submitType;
 	private String year;
 	private String veriforId;
 	private String targetId;
 	private String submitUserId;
 	//计算q2总分2套指标同时经行的时候所占的比例 格式为冒号分割 2:8 .
 	private String q2scorePer;
 	//计算q3总分2套指标同时经行的时候所占的比例 格式为冒号分割 2:8 .
 	private String q3scorePer;
 	//计算q4总分2套指标同时经行的时候所占的比例 格式为冒号分割 2:8 .
 	private String q4scorePer;
 	//是否已经接受绩效考核表.
 	private Short recived;

    public JxNom() {
    }

	
    public JxNom(String id, String year, String targetId) {
        this.id = id;
        this.year = year;
        this.targetId = targetId;
    }
    public JxNom(String id, String htFileId, String htFileName, Integer nomStatus, String orgL1name, String orgL2name, String orgName, Date psDate, Float q2finalScore, Float q3finalScore, Float q4finalScore, Date submitDate, Integer submitType, String year, String veriforId, String targetId, String submitUserId, String q2scorePer, String q3scorePer, String q4scorePer, Short recived) {
       this.id = id;
       this.htFileId = htFileId;
       this.htFileName = htFileName;
       this.nomStatus = nomStatus;
       this.orgL1name = orgL1name;
       this.orgL2name = orgL2name;
       this.orgName = orgName;
       this.psDate = psDate;
       this.q2finalScore = q2finalScore;
       this.q3finalScore = q3finalScore;
       this.q4finalScore = q4finalScore;
       this.submitDate = submitDate;
       this.submitType = submitType;
       this.year = year;
       this.veriforId = veriforId;
       this.targetId = targetId;
       this.submitUserId = submitUserId;
       this.q2scorePer = q2scorePer;
       this.q3scorePer = q3scorePer;
       this.q4scorePer = q4scorePer;
       this.recived = recived;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    /**       
     *      * this is doc info
     */
    public String getHtFileId() {
        return this.htFileId;
    }
    
    public void setHtFileId(String htFileId) {
        this.htFileId = htFileId;
    }
    public String getHtFileName() {
        return this.htFileName;
    }
    
    public void setHtFileName(String htFileName) {
        this.htFileName = htFileName;
    }
    public Integer getNomStatus() {
        return this.nomStatus;
    }
    
    public void setNomStatus(Integer nomStatus) {
        this.nomStatus = nomStatus;
    }
    public String getOrgL1name() {
        return this.orgL1name;
    }
    
    public void setOrgL1name(String orgL1name) {
        this.orgL1name = orgL1name;
    }
    public String getOrgL2name() {
        return this.orgL2name;
    }
    
    public void setOrgL2name(String orgL2name) {
        this.orgL2name = orgL2name;
    }
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    public Date getPsDate() {
        return this.psDate;
    }
    
    public void setPsDate(Date psDate) {
        this.psDate = psDate;
    }
    public Float getQ2finalScore() {
        return this.q2finalScore;
    }
    
    public void setQ2finalScore(Float q2finalScore) {
        this.q2finalScore = q2finalScore;
    }
    public Float getQ3finalScore() {
        return this.q3finalScore;
    }
    
    public void setQ3finalScore(Float q3finalScore) {
        this.q3finalScore = q3finalScore;
    }
    public Float getQ4finalScore() {
        return this.q4finalScore;
    }
    
    public void setQ4finalScore(Float q4finalScore) {
        this.q4finalScore = q4finalScore;
    }
    public Date getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }
    public Integer getSubmitType() {
        return this.submitType;
    }
    
    public void setSubmitType(Integer submitType) {
        this.submitType = submitType;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public String getVeriforId() {
        return this.veriforId;
    }
    
    public void setVeriforId(String veriforId) {
        this.veriforId = veriforId;
    }
    public String getTargetId() {
        return this.targetId;
    }
    
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }
    public String getSubmitUserId() {
        return this.submitUserId;
    }
    
    public void setSubmitUserId(String submitUserId) {
        this.submitUserId = submitUserId;
    }
    public String getQ2scorePer() {
        return this.q2scorePer;
    }
    
    public void setQ2scorePer(String q2scorePer) {
        this.q2scorePer = q2scorePer;
    }
    public String getQ3scorePer() {
        return this.q3scorePer;
    }
    
    public void setQ3scorePer(String q3scorePer) {
        this.q3scorePer = q3scorePer;
    }
    public String getQ4scorePer() {
        return this.q4scorePer;
    }
    
    public void setQ4scorePer(String q4scorePer) {
        this.q4scorePer = q4scorePer;
    }
    public Short getRecived() {
        return this.recived;
    }
    
    public void setRecived(Short recived) {
        this.recived = recived;
    }




}


