package com.zsq.test.model;
// Generated 2017-3-20 21:46:30 by J2EE-AUTOCODE Tools 4.3.5.Final

import java.util.Date;

/**
 * OrgUser generated by hbm2java exporter
 * @author AUTOCODE
 * @version $ID: OrgUser [BASE-LINE] 2017-3-20 21:46:30 $
 */
public class OrgUser  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	//class org.hibernate.mapping.Column
 	private String id;
	//class org.hibernate.mapping.Column
 	private Date activationTime;
	//class org.hibernate.mapping.Column
 	private Date applicationTime;
	//class org.hibernate.mapping.Column
 	private Integer creditLevel;
	//class org.hibernate.mapping.Column
 	private String deviceId;
	//class org.hibernate.mapping.Column
 	private String email;
	//class org.hibernate.mapping.Column
 	private Date firstLoginTime;
	//class org.hibernate.mapping.Column
 	private Boolean isSystem;
	//class org.hibernate.mapping.Column
 	private Date lastLoginTime;
	//class org.hibernate.mapping.Column
 	private String loginName;
	//class org.hibernate.mapping.Column
 	private Integer loginTimes;
	//class org.hibernate.mapping.Column
 	private String mobile;
	//class org.hibernate.mapping.Column
 	private String password;
	//class org.hibernate.mapping.Column
 	private String portrait;
	//class org.hibernate.mapping.Column
 	private Integer securityTag;
	//class org.hibernate.mapping.Column
 	private Integer sortOrder;
	//class org.hibernate.mapping.Column
 	private String sourceId;
	//class org.hibernate.mapping.Column
 	private String spell;
	//class org.hibernate.mapping.Column
 	private Integer userLevel;
	//class org.hibernate.mapping.Column
 	private Integer userSource;
	//class org.hibernate.mapping.Column
 	private int userStatus;
	//class org.hibernate.mapping.Column
 	private int userType;
	//class org.hibernate.mapping.Column
 	private Integer loginError;
	//class org.hibernate.mapping.Column
 	private int sapSyncStatus;
	//class org.hibernate.mapping.Column
 	private Date sapSyncDate;

    public OrgUser() {
    }

	
    public OrgUser(String id, String loginName, int userStatus, int userType, int sapSyncStatus) {
        this.id = id;
        this.loginName = loginName;
        this.userStatus = userStatus;
        this.userType = userType;
        this.sapSyncStatus = sapSyncStatus;
    }
    public OrgUser(String id, Date activationTime, Date applicationTime, Integer creditLevel, String deviceId, String email, Date firstLoginTime, Boolean isSystem, Date lastLoginTime, String loginName, Integer loginTimes, String mobile, String password, String portrait, Integer securityTag, Integer sortOrder, String sourceId, String spell, Integer userLevel, Integer userSource, int userStatus, int userType, Integer loginError, int sapSyncStatus, Date sapSyncDate) {
       this.id = id;
       this.activationTime = activationTime;
       this.applicationTime = applicationTime;
       this.creditLevel = creditLevel;
       this.deviceId = deviceId;
       this.email = email;
       this.firstLoginTime = firstLoginTime;
       this.isSystem = isSystem;
       this.lastLoginTime = lastLoginTime;
       this.loginName = loginName;
       this.loginTimes = loginTimes;
       this.mobile = mobile;
       this.password = password;
       this.portrait = portrait;
       this.securityTag = securityTag;
       this.sortOrder = sortOrder;
       this.sourceId = sourceId;
       this.spell = spell;
       this.userLevel = userLevel;
       this.userSource = userSource;
       this.userStatus = userStatus;
       this.userType = userType;
       this.loginError = loginError;
       this.sapSyncStatus = sapSyncStatus;
       this.sapSyncDate = sapSyncDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Date getActivationTime() {
        return this.activationTime;
    }
    
    public void setActivationTime(Date activationTime) {
        this.activationTime = activationTime;
    }
    public Date getApplicationTime() {
        return this.applicationTime;
    }
    
    public void setApplicationTime(Date applicationTime) {
        this.applicationTime = applicationTime;
    }
    public Integer getCreditLevel() {
        return this.creditLevel;
    }
    
    public void setCreditLevel(Integer creditLevel) {
        this.creditLevel = creditLevel;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFirstLoginTime() {
        return this.firstLoginTime;
    }
    
    public void setFirstLoginTime(Date firstLoginTime) {
        this.firstLoginTime = firstLoginTime;
    }
    public Boolean getIsSystem() {
        return this.isSystem;
    }
    
    public void setIsSystem(Boolean isSystem) {
        this.isSystem = isSystem;
    }
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public Integer getLoginTimes() {
        return this.loginTimes;
    }
    
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPortrait() {
        return this.portrait;
    }
    
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }
    public Integer getSecurityTag() {
        return this.securityTag;
    }
    
    public void setSecurityTag(Integer securityTag) {
        this.securityTag = securityTag;
    }
    public Integer getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
    public String getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }
    public String getSpell() {
        return this.spell;
    }
    
    public void setSpell(String spell) {
        this.spell = spell;
    }
    public Integer getUserLevel() {
        return this.userLevel;
    }
    
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }
    public Integer getUserSource() {
        return this.userSource;
    }
    
    public void setUserSource(Integer userSource) {
        this.userSource = userSource;
    }
    public int getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(int userStatus) {
        this.userStatus = userStatus;
    }
    public int getUserType() {
        return this.userType;
    }
    
    public void setUserType(int userType) {
        this.userType = userType;
    }
    public Integer getLoginError() {
        return this.loginError;
    }
    
    public void setLoginError(Integer loginError) {
        this.loginError = loginError;
    }
    public int getSapSyncStatus() {
        return this.sapSyncStatus;
    }
    
    public void setSapSyncStatus(int sapSyncStatus) {
        this.sapSyncStatus = sapSyncStatus;
    }
    public Date getSapSyncDate() {
        return this.sapSyncDate;
    }
    
    public void setSapSyncDate(Date sapSyncDate) {
        this.sapSyncDate = sapSyncDate;
    }




}


